lightning:
  _target_: world-of-bugs-experiments.module.AELightningModule

  model: 
    _target_: world-of-bugs-experiments.module.AE
    
  criterion: 
    _target_: world-of-bugs-experiments.module.MSESSIM #torch.nn.MSELoss

  score:  # anomaly score
    _target_: ${..criterion._target_}
    reduction: 'none'
    
  metrics: 
    - _target_: world-of-bugs-experiments.module.ROC                          # ROC curve
    - _target_: world-of-bugs-experiments.module.PrecisionRecall              # PR curve
    #- _target_: world-of-bugs-experiments.module.AccuracyPrecisionRecallF1    # flat accuracy, precision, recall for different threshold values
  optimiser:
    _target_: torch.optim.Adam
    lr: 0.0005

data:
  _target_: world-of-bugs-experiments.data.WOBDataModule
  path: ${hydra:runtime.cwd}/dataset
  force: false
  in_memory: false
  shuffle_buffer_size: 20000
  initial_buffer_size: 10000
  prefetch_factor: 16
  batch_size: 256
  num_workers: 32
  train_mode: ['state']
  test_mode: ['state', 'info']
  train_files: "NORMAL-TRAIN/*/*.tar"
  validation_files: "NORMAL-TRAIN-SMALL/*/*-0000.tar"
  test_files: "TEST/*/*/*.tar"
  
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  max_epochs: 20
  min_epochs: 20
  check_val_every_n_epoch: 1
  #profiler: simple
  logger: 
    _target_: pytorch_lightning.loggers.WandbLogger
    project: WOB-Experiments
    log_model: all
    mode: online



    




    