lightning:
  _target_: world-of-bugs-experiments.module.AELightningModule
  model: 
    _target_: world-of-bugs-experiments.module.AE
    input_shape: [3,84,84]
    latent_shape: [512]
  criterion: 
    _target_: torch.nn.MSELoss
  score:  # anomaly score
    _target_: ${..criterion._target_}
    reduction: 'none'
  metrics: 
    - _target_: world-of-bugs-experiments.module.ROC
    - _target_: world-of-bugs-experiments.module.PrecisionRecall

  optimiser:
    _target_: torch.optim.Adam
    lr: 0.005

data:
  _target_: world-of-bugs-experiments.data.WOBDataModule
  path: ${hydra:runtime.cwd}/dataset
  force: false
  shuffle_buffer_size: 10000
  initial_buffer_size: 10000
  prefetch_factor: 16
  batch_size: 256
  num_workers: 12 
  train_mode: ['state']
  test_mode: ['state', 'info']
  train_files: "NORMAL-TRAIN/*.tar.gz"
  validation_files: "NORMAL-TRAIN-SMALL/*-0000.tar.gz"
  test_files: "TEST/*/*-0000.tar.gz"
  
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  max_epochs: 100
  min_epochs: 100
  check_val_every_n_epoch: 1
  logger: 
    _target_: pytorch_lightning.loggers.WandbLogger
    project: WOB-Experiments
    log_model: all
    mode: online



    




    